% for all hemispheres, for all regions, for all subjects
% read timecourses of the format hemi.region.wmvcsf.dat
% load them into a matrix of timecourses across subjects

%destination
TC_path = '/Users/caramazzalab/Desktop/Jess/timecourses';

%TRs
TRs = 240;

%hemispheres
hemis = ["lh"; "rh"];
n_h = size(hemis, 1);

%regions
regions = [ ...
    "BA1_exvivo"; ...
    "BA2_exvivo"; ...
    "BA3a_exvivo"; ...
    "BA3b_exvivo"; ...
    "BA4a_exvivo"; ...
    "BA4p_exvivo"; ...
    "BA6_exvivo"; ...
    "BA44_exvivo"; ...
    "BA45_exvivo"; ...
    "cortex"; ...
    "entorhinal_exvivo"; ...
    "MT_exvivo"; ...
    "perirhinal_exvivo"; ...
    "V1_exvivo"; ...
    "V2_exvivo"; ...
];
n_r = size(regions, 1);

%subject functional files
subjects = [ ...
%     "B101"; ...
%     "B102"; ...
%     "B103"; ...
%     "B104"; ...
%     "B105"; ...
%     "B106"; ...
%     "B107"; ...
%     "B108"; ...
%     "B109"; ...
%     "B111"; ...
%     "B112"; ...
    "S201"; ...
    "S203"; ...
    "S204"; ...
    "S205"; ...
    "S206"; ...
    "S207"; ...
    "S208"; ...
    "S209"; ...
    "S212"; ...
    "S213"; ...
    "S214"; ...
    "S215"; ...
    "S216"; ...
]; 
n_s = size(subjects,1);

%dimensions of the matrix
TC_mat = zeros(n_h * n_r, TRs, n_s);

%generate a legend for the ROIs
% called: ROI_legend
ROI_ind = 1;
for h = 1 : n_h
    hemi = hemis(h);
    for r = 1: n_r
        region = regions(r);
            name = strcat(hemi, ".", region);
            ROI_legend(ROI_ind, 2) = name;
            ROI_legend(ROI_ind, 1) = int2str(ROI_ind);
            ROI_ind = ROI_ind + 1;
    end
end

%generate a legend for the subjects
% called: subj_legend
for s = 1 : n_s
    subject = subjects(s);
    subj_legend(s, 2) = subject;
    subj_legend(s, 1) = int2str(s);
    ROI_ind = 1;
    for h = 1 : n_h
        hemi = hemis(h);
        for r = 1: n_r
            region = regions(r);

            s_path = char(strcat( ...
                '/Users/caramazzalab/Desktop/Jess/V1_REST_STUDY/dicomdir/'...
                , subject, '/bold/001'));
            addpath(s_path);
            % Generate a timecourse for region
            file_str = strcat(hemi, ".", region, ".wmvcsf.dat");
            TC = dlmread([s_path '/' char(file_str)]);
            
            % Pad TC with Zeros at the end
            if (length(TC) < 240)
                TC = [TC; zeros(TRs - length(TC), 1)];
            end
            
            TC_mat(ROI_ind, :, s) = TC;
            
            ROI_ind = ROI_ind + 1;
        end
    end
end

save('sight_TC_mat.mat', 'TC_mat', 'ROI_legend', 'subj_legend');
movefile('sight_TC_mat.mat', TC_path);