% this script was necessary because I mispelled a file extension and
% need to rename them all with the movefile function

%hemispheres
hemis = ["lh"; "rh"];
n_h = size(hemis, 1);

%regions
regions = [ ...
    "BA1_exvivo"; ...
    "BA2_exvivo"; ...
    "BA3a_exvivo"; ...
    "BA3b_exvivo"; ...
    "BA4a_exvivo"; ...
    "BA4p_exvivo"; ...
    "BA6_exvivo"; ...
    "BA44_exvivo"; ...
    "BA45_exvivo"; ...
    "cortex"; ...
    "entorhinal_exvivo"; ...
    "MT_exvivo"; ...
    "perirhinal_exvivo"; ...
    "V1_exvivo"; ...
    "V2_exvivo"; ...
];
n_r = size(regions, 1);

%subject functional files
subjects = [ ...
    "B101"; ...
    "B102"; ...
    "B103"; ...
    "B104"; ...
    "B105"; ...
    "B106"; ...
    "B107"; ...
    "B108"; ...
    "B109"; ...
    "B111"; ...
    "B112"; ...
    "S201"; ...
    "S203"; ...
    "S204"; ...
    "S205"; ...
    "S206"; ...
    "S207"; ...
    "S208"; ...
    "S209"; ...
    "S212"; ...
    "S213"; ...
    "S214"; ...
    "S215"; ...
    "S216"; ...
]; 
n_s = size(subjects,1);

for h = 1 : n_h
    hemi = hemis(h);
    for r = 1: n_r
        region = regions(r);
        for s = 1 : n_s
            subject = subjects(s);
            s_path = char(strcat( ...
                '/Users/caramazzalab/Desktop/Jess/V1_REST_STUDY/dicomdir/'...
                , subject, '/bold/001'));
            addpath(s_path);
            file_str = strcat(hemi, ".", region, ".wmvscf.dat");
            file_char = [s_path '/' char(file_str)];
            new_file_str = strcat(hemi, ".", region, ".wmvcsf.dat");
            new_file_char = [s_path '/' char(new_file_str)];
            
            %rename the file
            movefile(file_char, new_file_char);
        end
    end
end